<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJhcjEnp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJhcjEnp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJhcjEnp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJhcjEnp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJhcjEnp\App_KernelDevDebugContainer([
    'container.build_hash' => 'JhcjEnp',
    'container.build_id' => '29c55f5e',
    'container.build_time' => 1684693451,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJhcjEnp');
