<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU9xO0MK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU9xO0MK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU9xO0MK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU9xO0MK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU9xO0MK\App_KernelDevDebugContainer([
    'container.build_hash' => 'U9xO0MK',
    'container.build_id' => '6d81ac3d',
    'container.build_time' => 1684679829,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU9xO0MK');
